import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../shared/header";
import Footer from "../shared/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Starter App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* header */}
        <Header />

        {children}

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
